name: Update Notation Sheet and Exam Simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2

      # OPTIONAL: Install dependencies or run build scripts if needed
      # - name: Run your build script
      #   run: sh ./build.sh

      # Push notationSheet for main branch
      - name: Push notationSheet to another repository (main)
        id: push_notation_main
        uses: cpina/github-action-push-to-another-repository@main
        if: github.ref == 'refs/heads/main'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./files/
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
          target-directory: ./notationSheet/

      # Push notationSheet for dev branch
      - name: Push notationSheet to another repository (dev)
        id: push_notation_dev
        uses: cpina/github-action-push-to-another-repository@main
        if: github.ref == 'refs/heads/dev'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./files/
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
          target-directory: ./notationSheet/dev/

      # Clone DECA-ExamSimulator repo
      - name: Clone DECA-ExamSimulator
        uses: actions/checkout@v4
        with:
          repository: JaxGM/DECA-ExamSimulator
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: deca-exam-simulator

      # Push DECA-ExamSimulator contents to your Pages repo
      - name: Push DECA-ExamSimulator to another repository
        id: push_exam_simulator
        uses: cpina/github-action-push-to-another-repository@main
        if: github.ref == 'refs/heads/main'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./deca-exam-simulator/
          destination-github-username: 'JaxGM'
          destination-repository-name: 'JaxGM.github.io'
          user-email: flume_prowl_0n@icloud.com
          target-branch: main
          target-directory: ./examSimulator/
